// <auto-generated />
namespace CursoASPNETMVC2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreaciontablasPersonatarjetacreditocursoDireccion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreaciontablasPersonatarjetacreditocursoDireccion));
        
        string IMigrationMetadata.Id
        {
            get { return "201903051459288_Creacion tablas Persona, tarjetacredito,curso,Direccion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
