// <auto-generated />
namespace Sqlinjection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProcedimientoAlmacenado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProcedimientoAlmacenado));
        
        string IMigrationMetadata.Id
        {
            get { return "201903191309583_ProcedimientoAlmacenado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
